name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish-nuget:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Build Package
      run: dotnet pack --configuration Release
    - name: Publish to Github Packages
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: txte/txte.csproj
        NUGET_SOURCE: https://nuget.pkg.github.com/planifolia/index.json
        VERSION_REGEX: '^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$'
        TAG_COMMIT: true
        TAG_FORMAT: 'v*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
