name: Publish Nuget Package

on: [ workflow_dispatch]

jobs:
  publish-nuget:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Publish to Github Packages
      uses: Rebel028/publish-nuget@v2.6.0
      with:
        PROJECT_FILE_PATH: txte/txte.csproj
        NUGET_SOURCE: https://nuget.pkg.github.com/planifolia
        VERSION_REGEX: '^\s*<Version>(.*)<\/Version>\s*$'
        TAG_COMMIT: true
        TAG_FORMAT: 'v*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
